/**
 * 筛选器分类数据配置
 * @description 所有筛选分类配置都在这里管理
 */

// 视频相关分类
const videoCategories = [
  {
    key: 'category',
    name: '分类',
    children: [
      { value: 'movie', name: '电影' },
      { value: 'tv', name: '电视剧' },
      { value: 'anime', name: '动画' },
      { value: 'doc', name: '纪录片' },
      { value: 'cartoon', name: '动漫' },
      { value: 'variety', name: '综艺' },
      { value: 'culture', name: '文化' },
      { value: 'kids', name: '少儿' },
      { value: 'family', name: '亲子' },
      { value: 'education', name: '教育' },
      { value: 'comedy', name: '搞笑' },
      { value: 'life', name: '生活' },
      { value: 'tech', name: '科技' },
      { value: 'entertainment', name: '娱乐' },
      { value: 'sports', name: '体育' },
      { value: 'fashion', name: '时尚' },
      { value: 'music', name: '音乐' },
      { value: 'game', name: '游戏' },
      { value: 'comic', name: '漫画' },
      { value: 'novel', name: '小说' },
    ],
  },
  {
    key: 'type',
    name: '全部类型',
    children: [
      { value: 'military_life', name: '军旅' },
      { value: 'military', name: '军事' },
      { value: 'espionage', name: '谍战' },
      { value: 'idol', name: '偶像' },
      { value: 'time_travel', name: '穿越' },
      { value: 'xianxia', name: '仙侠' },
      { value: 'family', name: '家庭' },
      { value: 'rural', name: '农村' },
      { value: 'romance', name: '情感' },
      { value: 'sports', name: '体育' },
      { value: 'crosstalk', name: '相声' },
      { value: 'marriage', name: '婚恋' },
      { value: 'fashion', name: '时尚' },
      { value: 'gala', name: '晚会' },
      { value: 'food', name: '美食' },
      { value: 'travel', name: '旅游' },
      { value: 'reality', name: '真人' },
      { value: 'book_story', name: '绘本故事' },
      { value: 'toy', name: '玩具' },
      { value: 'action', name: '动作' },
      { value: 'comedy', name: '喜剧' },
      { value: 'monster', name: '怪兽' },
      { value: 'war', name: '战争' },
      { value: 'mystery', name: '悬疑' },
      { value: 'wuxia', name: '武侠' },
      { value: 'romance', name: '爱情' },
      { value: 'drama', name: '剧情' },
      { value: 'scifi', name: '科幻' },
      { value: 'horror', name: '恐怖' },
      { value: 'fantasy', name: '奇幻' },
      { value: 'adventure', name: '冒险' },
      { value: 'crime_police', name: '警匪' },
      { value: 'animation', name: '动画' },
      { value: 'thriller', name: '惊悚' },
      { value: 'crime', name: '犯罪' },
      { value: 'history', name: '历史' },
      { value: 'documentary', name: '纪录片' },
      { value: 'biography', name: '传记' },
      { value: 'musical', name: '歌舞' },
      { value: 'short_film', name: '短片' },
      { value: 'sports', name: '运动' },
      { value: 'nature', name: '自然' },
      { value: 'adventure', name: '探险' },
      { value: 'universe', name: '宇宙' },
      { value: 'crime_investigation', name: '刑侦' },
      { value: 'society', name: '社会' },
      { value: 'technology', name: '科技' },
      { value: 'knowledge', name: '知识' },
      { value: 'talk_show', name: '谈话' },
      { value: 'talk_show', name: '脱口秀' },
      { value: 'interview', name: '访谈' },
      { value: 'traditional_opera', name: '戏曲曲艺' },
      { value: 'literature', name: '文学' },
      { value: 'sinology', name: '国学' },
      { value: 'art', name: '艺术' },
      { value: 'audiobook', name: '有声书' },
      { value: 'beauty', name: '美妆' },
      { value: 'open_course', name: '公开课' },
      { value: 'ethics', name: '伦理' },
      { value: 'science_and_engineering', name: '理工' },
      { value: 'psychology', name: '心理学' },
      { value: 'economics', name: '经济' },
      { value: 'management', name: '管理学' },
      { value: 'law', name: '法律' },
      { value: 'computer_science', name: '计算机' },
      { value: 'philosophy', name: '哲学' },
      { value: 'family_education', name: '家庭教育' },
      { value: 'basketball', name: '篮球' },
      { value: 'football', name: '足球' },
      { value: 'billiards', name: '台球' },
      { value: 'cba', name: 'cba' },
      { value: 'fishing', name: '钓鱼' },
      { value: 'concert', name: '演唱会' },
      { value: 'live_performance', name: 'Live现场' },
      { value: 'award_ceremony', name: '颁奖典礼' },
      { value: 'dance', name: '舞蹈' },
      { value: 'film_soundtracks', name: '影视原声' },
      { value: 'music_talent', name: '音乐达人' },
      { value: 'music_lessons', name: '音乐教学' },
      { value: 'music_video', name: '音乐MV' },
      { value: 'story_animation', name: '剧情动画' },
      { value: 'commentary', name: '解说实况' },
      { value: 'gaming_news', name: '游戏资讯' },
      { value: 'ip_series', name: 'IP系列' },
      { value: 'tournament', name: '电竞赛事' },
      { value: 'game_show', name: '游戏综艺' },
      { value: 'game_review', name: '游戏评测' },
      { value: 'game_news', name: '游戏新闻' },
      { value: 'game_guides', name: '游戏攻略' },
      { value: 'game_trailer', name: '游戏预告' },
      { value: 'stream', name: '直播' },
      { value: 'ai', name: 'ai' },
      { value: 'other', name: '其他' },
    ],
  },
  {
    key: 'area',
    name: '全部地区',
    children: [
      { value: 'china', name: '中国大陆' },
      { value: 'hongkong', name: '中国香港' },
      { value: 'taiwan', name: '中国台湾' },
      { value: 'japan', name: '日本' },
      { value: 'korea', name: '韩国' },
      { value: 'usa', name: '美国' },
      { value: 'europe', name: '欧洲' },
      { value: 'india', name: '印度' },
      { value: 'uk', name: '英国' },
      { value: 'france', name: '法国' },
      { value: 'thailand', name: '泰国' },
      { value: 'singapore', name: '新加坡' },
      { value: 'malaysia', name: '马来西亚' },
      { value: 'indonesia', name: '印度尼西亚' },
      { value: 'philippines', name: '菲律宾' },
      { value: 'vietnam', name: '越南' },
      { value: 'brazil', name: '巴西' },
      { value: 'argentina', name: '阿根廷' },
      { value: 'colombia', name: '哥伦比亚' },
      { value: 'mexico', name: '墨西哥' },
      { value: 'peru', name: '秘鲁' },
      { value: 'chile', name: '智利' },
      { value: 'germany', name: '德国' },
      { value: 'poland', name: '波兰' },
      { value: 'other_country', name: '其他国家' },
    ],
  },
  {
    key: 'year',
    name: '全部年代',
    children: [
      { value: '2024', name: '2024' },
      { value: '2023', name: '2023' },
      { value: '2022', name: '2022' },
      { value: '2021', name: '2021' },
      { value: '2020', name: '2020' },
      { value: '2019', name: '2019' },
      { value: '2018', name: '2018' },
      { value: '2017', name: '2017' },
      { value: '2016', name: '2016' },
      { value: '2015', name: '2015' },
      { value: '2014', name: '2014' },
      { value: '2013', name: '2013' },
      { value: '2012', name: '2012' },
      { value: '2011', name: '2011' },
      { value: '2010', name: '2010' },
      { value: '2009', name: '2009' },
      { value: '2008', name: '2008' },
      { value: '2007', name: '2007' },
      { value: '2006', name: '2006' },
      { value: '2005', name: '2005' },
      { value: '2004', name: '2004' },
      { value: '2003', name: '2003' },
      { value: '2002', name: '2002' },
      { value: '2001', name: '2001' },
      { value: '2000', name: '2000' },
      { value: '90s', name: '90年代' },
      { value: '80s', name: '80年代' },
      { value: '70s', name: '70年代' },
      { value: 'earlier', name: '更早' },
    ],
  },
  {
    key: 'specification',
    name: '全部规格',
    children: [
      { value: 'exclusive', name: '独播' },
      { value: 'completed', name: '已完结' },
      { value: 'ongoing', name: '连载中' },
      { value: 'updating', name: '更新中' },
      { value: 'upcoming', name: '即将上线' },
      { value: 'bilibili_original', name: 'bilibili出品' },
      { value: 'youku_original', name: '优酷出品' },
      { value: 'iqiyi_original', name: '爱奇艺出品' },
      { value: 'tencent_original', name: '腾讯出品' },
      { value: 'short_drama', name: '短剧' },
      { value: 'self_produced', name: '自制' },
      { value: 'cinema', name: '院线' },
      { value: 'web_movie', name: '网络电影' },
      { value: 'hd_restoration', name: '高清修复' },
      { value: '4k', name: '4K' },
      { value: '2k', name: '2K' },
      { value: '1080P', name: '1080P' },
      { value: 'cantonese', name: '粤语' },
      { value: 'mandarin', name: '国语' },
      { value: 'japanese', name: '日语' },
      { value: 'english', name: '英语' },
      { value: 'french', name: '法语' },
      { value: 'korean', name: '韩语' },
      { value: 'russian', name: '俄语' },
      { value: 'hindi', name: '印度语' },
      { value: 'arabic', name: '阿拉伯语' },
      { value: 'action', name: '热血' },
      { value: 'inspirational', name: '励志' },
      { value: 'fantasy', name: '玄幻' },
      { value: 'ancient_costume', name: '古装' },
      { value: 'ancient_style', name: '古风' },
      { value: 'dynamic_manga', name: '动态漫' },
      { value: 'romance', name: '恋爱' },
      { value: 'youth', name: '青春' },
      { value: 'school_life', name: '校园' },
      { value: 'sports', name: '运动' },
      { value: 'science_fiction', name: '科幻' },
      { value: 'adventure', name: '冒险' },
      { value: 'magic', name: '魔法' },
      { value: 'daily_life', name: '日常' },
      { value: 'healing', name: '治愈' },
      { value: 'mecha', name: '机战' },
      { value: 'mystery', name: '推理' },
      { value: 'urban', name: '都市' },
      { value: 'special_effects', name: '特摄' },
      { value: 'novel_adaptation', name: '小说改' },
      { value: 'game_adaptation', name: '游戏改' },
      { value: 'manga_adaptation', name: '漫画改' },
      { value: 'puppetry', name: '布袋戏' },
      { value: 'intelligence', name: '益智' },
      { value: 'humor', name: '幽默' },
      { value: 'mech', name: '机甲' },
      { value: 'vehicles', name: '交通工具' },
      { value: 'dinosaurs', name: '恐龙' },
      { value: 'animals', name: '动物' },
      { value: 'friendship', name: '友情' },
      { value: 'battle', name: '战斗' },
      { value: 'justice', name: '正义' },
      { value: 'fairy_tale', name: '童话' },
      { value: 'science_education', name: '科普' },
      { value: 'emotional_intelligence', name: '情商' },
      { value: 'concentration', name: '专注力' },
      { value: 'creativity', name: '创造力' },
      { value: 'imagination', name: '想象力' },
      { value: 'logical_thinking', name: '思维逻辑' },
      { value: 'interest_cultivation', name: '兴趣培养' },
      { value: 'course', name: '课程' },
    ],
  },
  {
    key: 'payment',
    name: '付费类型',
    children: [
      { value: 'free', name: '免费' },
      { value: 'paid', name: '付费' },
      { value: 'vip', name: '会员' },
      { value: 'vip_free', name: '会员免费' },
      { value: 'limited_free', name: '限免中' },
    ],
  },
  {
    key: 'comprehensive_sorting',
    name: '综合排序',
    children: [
      { value: 'highest_heat', name: '热度最高' },
      { value: 'latest_release', name: '最新上线' },
      { value: 'most_reviews_positive', name: '最多好评' },
      { value: 'most_reviews_negative', name: '最多差评' },
      { value: 'most_views', name: '最多播放' },
      { value: 'most_comments', name: '最多评论' },
      { value: 'most_follows', name: '最多关注' },
      { value: 'most_collections', name: '最多收藏' },
      { value: 'most_likes', name: '最多点赞' },
      { value: 'most_watches', name: '最多观看' },
      { value: 'recently_live', name: '最近开播' },
      { value: 'latest_update', name: '最新更新' },
      { value: 'most_downloads', name: '最多下载' },
      { value: 'recent_updates', name: '最近更新' },
      { value: 'most_awards', name: '最多获奖' },
    ],
  },
  {
    key: 'grading',
    name: '全部分级',
    children: [
      { value: 'G-U', name: '全家适宜' },
      { value: 'PG', name: '建议家长指导' },
      { value: '12A', name: '12岁以上适宜' },
      { value: 'PG-13', name: '建议13岁以上观看' },
      { value: '15', name: '15岁以上适宜' },
      { value: 'R', name: '17岁以下需成人陪同' },
      { value: 'NC-17', name: '17岁以下不得观看' },
      { value: '18', name: '18岁以上适宜' },
      { value: 'X', name: '静止未成年人观看' },
      { value: 'EC-3', name: '适用于3岁以上儿童' },
      { value: 'E', name: '适用于所有人' },
      { value: '7', name: '适用于7岁以上' },
      { value: 'E10+', name: '适用于10岁以上' },
      { value: '12', name: '适用于12岁以上' },
      { value: 'T', name: '适用于13岁以上' },
      { value: 'M16', name: '适用于16岁以上' },
      { value: 'M', name: '适用于17岁以上' },
      { value: 'AO', name: '仅适用于18岁以上' },
      { value: '18', name: '仅适用于成年人' },
      { value: 'all_ages', name: '全年龄段' },
      { value: 'children', name: '儿童' },
      { value: 'teen', name: '青少年' },
      { value: 'adult', name: '成人' },
      { value: 'safe', name: '安全' },
      { value: 'sfw', name: '内容不包含任何露骨性质的内容' },
      { value: 'nsfw', name: '内容可能含有露骨（性、暴力等）性质' },
    ],
  },
  {
    key: 'productions',
    name: '全部出品',
    children: [
      { value: 'universal', name: 'Universal Pictures' }, // 环球影业
      { value: 'disney', name: 'Walt Disney Studios' }, // 迪士尼
      { value: 'sony', name: 'Sony Pictures Entertainment' }, // 索尼
      { value: 'paramount', name: 'Paramount Pictures' }, // 派拉蒙
      { value: 'warner', name: 'Warner Bros. Pictures' }, // 华纳
      { value: 'shaw', name: 'Shaw Brothers Studio' }, // 邵氏
      { value: 'marvel', name: 'Marvel Studios' }, // 漫威
      { value: 'dc', name: 'DC Films' }, // DC
      { value: 'pixar', name: 'Pixar Animation Studios' }, // 皮克斯
      { value: 'dreamworks', name: 'DreamWorks Animation' }, // 梦工厂
      { value: 'illumination', name: 'Illumination Entertainment' }, // 照明娱乐
      { value: 'galaxy', name: 'Galaxy Studio' }, // 银河映像
      { value: 'happyMahua', name: 'Happy Mahua Pictures' }, // 开心麻花
      { value: 'emperor', name: 'Emperor Entertainment Group' }, // 英皇
      { value: 'lightChaser', name: 'Light Chaser Animation' }, // 追光动画
      { value: '20thCentury', name: '20th Century Studios' }, // 20世纪影业
      { value: 'a24', name: 'A24' }, // A24
      { value: 'netflix', name: 'Netflix' }, // Netflix
    ],
  },
]

// 书籍相关分类
const bookCategories = [
  {
    key: 'type',
    name: '类型',
    children: [
      { value: 'novel', name: '小说' },
      { value: 'fiction_novel', name: '虚构小说' },
      { value: 'classical_literature', name: '古典文学' },
      { value: 'modern_literature', name: '现代文学' },
      { value: 'contemporary_literature', name: '当代文学' },
      { value: 'science_fiction', name: '科幻小说' },
      { value: 'fantasy', name: '奇幻小说' },
      { value: 'martial_arts', name: '武侠小说' },
      { value: 'xianxia', name: '仙侠小说' },
      { value: 'urban', name: '都市小说' },
      { value: 'historical', name: '历史小说' },
      { value: 'military', name: '军事小说' },
      { value: 'detective', name: '侦探小说' },
      { value: 'thriller', name: '惊悚小说' },
      { value: 'romance', name: '言情小说' },
      { value: 'danmei', name: '耽美小说' },
      { value: 'lily', name: '百合小说' },
      { value: 'light_novel', name: '轻小说' },
      { value: 'web_novel', name: '网络小说' },
      { value: 'children_literature', name: '儿童文学' },
      { value: 'picture_book', name: '绘本' },
      { value: 'biography', name: '传记' },
      { value: 'autobiography', name: '自传' },
      { value: 'history', name: '历史' },
      { value: 'philosophy', name: '哲学' },
      { value: 'religion', name: '宗教' },
      { value: 'psychology', name: '心理学' },
      { value: 'sociology', name: '社会学' },
      { value: 'politics', name: '政治' },
      { value: 'economics', name: '经济学' },
      { value: 'business', name: '商业' },
      { value: 'management', name: '管理学' },
      { value: 'finance', name: '金融学' },
      { value: 'law', name: '法律' },
      { value: 'science', name: '科学' },
      { value: 'technology', name: '技术' },
      { value: 'engineering', name: '工程' },
      { value: 'medicine', name: '医学' },
      { value: 'art', name: '艺术' },
      { value: 'music', name: '音乐' },
      { value: 'film', name: '电影' },
      { value: 'drama', name: '戏剧' },
      { value: 'travel', name: '旅游' },
      { value: 'food', name: '美食' },
      { value: 'cooking', name: '烹饪' },
      { value: 'self_help', name: '自助' },
      { value: 'reference', name: '参考' },
      { value: 'textbook', name: '教材' },
      { value: 'exam', name: '考试' },
      { value: 'language', name: '语言' },
      { value: 'literary_criticism', name: '文学批评' },
      { value: 'essay', name: '散文' },
      { value: 'poetry', name: '诗歌' },
      { value: 'play', name: '剧本' },
      { value: 'life', name: '生活' },
    ],
  },
  {
    key: 'genre',
    name: '题材',
    children: [
      { value: 'fantasy', name: '玄幻奇幻' },
      { value: 'cultivation', name: '修真' },
      { value: 'dynasty_struggle', name: '王朝争霸' },
      { value: 'alien_ability', name: '异术超能' },
      { value: 'ancient_myth', name: '远古神话' },
      { value: 'reincarnation', name: '转世重生' },
      { value: 'parallel_world', name: '异世大陆' },
      { value: 'romance', name: '言情' },
      { value: 'pure_love', name: '纯爱唯美' },
      { value: 'adventure_romance', name: '冒险推理' },
      { value: 'ancient_romance', name: '古代言情' },
      { value: 'court_intrigue', name: '宫廷争斗' },
      { value: 'female_empire', name: '女尊王朝' },
      { value: 'modern_romance', name: '现代言情' },
      { value: 'office_love', name: '爱在职场' },
      { value: 'campus_love', name: '菁菁校园' },
      { value: 'mystery', name: '悬疑推理' },
      { value: 'detective', name: '侦探推理' },
      { value: 'thriller', name: '惊悚悬疑' },
      { value: 'supernatural_mystery', name: '灵异悬疑' },
      { value: 'historical', name: '历史' },
      { value: 'alternate_history', name: '架空历史' },
      { value: 'historical_biography', name: '历史传记' },
      { value: 'travel_back', name: '穿越古代' },
      { value: 'foreign_history', name: '外国历史' },
      { value: 'science_fiction', name: '科幻' },
      { value: 'machine_age', name: '机器时代' },
      { value: 'cybernetic_space', name: '骇客时空' },
      { value: 'digital_life', name: '数字生命' },
      { value: 'interstellar_war', name: '星际战争' },
      { value: 'ancient_mecha', name: '古武机甲' },
      { value: 'time_travel', name: '时空穿梭' },
      { value: 'apocalyptic_future', name: '末世危机' },
      { value: 'evolution_mutation', name: '进化变异' },
      { value: 'martial_arts', name: '武侠' },
      { value: 'traditional_martial_arts', name: '传统武侠' },
      { value: 'new_martial_arts', name: '新派武侠' },
      { value: 'martial_arts_fantasy', name: '武侠幻想' },
      { value: 'historical_martial_arts', name: '历史武侠' },
      { value: 'roaming_hero', name: '浪子异侠' },
      { value: 'humorous_martial_arts', name: '谐趣武侠' },
      { value: 'heroic_martial_arts', name: '快意江湖' },
      { value: 'urban', name: '都市' },
      { value: 'urban_life', name: '都市生活' },
      { value: 'youth_campus', name: '青春校园' },
      { value: 'urban_rebirth', name: '都市重生' },
      { value: 'shared_apartment', name: '合租情缘' },
      { value: 'entertainment_star', name: '娱乐明星' },
      { value: 'spy_agent', name: '谍战特工' },
      { value: 'love_marriage', name: '爱情婚姻' },
      { value: 'native_soil', name: '乡土' },
      { value: 'martial_arts_skill', name: '国术武技' },
      { value: 'president_love', name: '总裁虐恋' },
      { value: 'officialdom', name: '官场沉浮' },
      { value: 'business_market', name: '商场职场' },
      { value: 'military', name: '军事' },
      { value: 'war_history', name: '战争历史' },
      { value: 'modern_military', name: '现代军事' },
      { value: 'military_fiction', name: '军事科幻' },
      { value: 'military_game', name: '军事游戏' },
      { value: 'game', name: '游戏' },
      { value: 'holographic_game', name: '全息网游' },
      { value: 'game_career', name: '游戏生涯' },
      { value: 'e_sports', name: '电子竞技' },
      { value: 'game_otherworld', name: '游戏异界' },
      { value: 'sports', name: '体育' },
      { value: 'chess_career', name: '弈林生涯' },
      { value: 'basketball', name: '篮球运动' },
      { value: 'football', name: '足球运动' },
      { value: 'tennis', name: '网球运动' },
      { value: 'sports_event', name: '体育赛事' },
      { value: 'horror', name: '恐怖惊悚' },
      { value: 'ghost_story', name: '鬼故事' },
      { value: 'zombie', name: '僵尸' },
      { value: 'monster', name: '怪物' },
      { value: 'psychological_horror', name: '心理恐怖' },
      { value: 'biography', name: '传记' },
      { value: 'personal_biography', name: '个人传记' },
      { value: 'celebrity_biography', name: '名人传记' },
      { value: 'historical_figure', name: '历史人物传记' },
      { value: 'children', name: '儿童文学' },
      { value: 'fairy_tale', name: '童话' },
      { value: 'adventure_story', name: '冒险故事' },
      { value: 'science_story', name: '科普故事' },
      { value: 'poetry', name: '诗歌' },
      { value: 'classical_poetry', name: '古典诗歌' },
      { value: 'modern_poetry', name: '现代诗歌' },
      { value: 'essay', name: '散文' },
      { value: 'narrative_essay', name: '记叙文' },
      { value: 'lyrical_essay', name: '抒情文' },
      { value: 'argumentative_essay', name: '议论文' },
      { value: 'transmigration', name: '穿越' },
      { value: 'cross_time_space', name: '穿越时空' },
      { value: 'travel_future', name: '穿越未来' },
      { value: 'body_transmigration', name: '身体穿越' },
      { value: 'soul_transmigration', name: '灵魂穿越' },
      { value: 'parallel_world', name: '平行世界' },
      { value: 'parallel_fantasy', name: '平行玄幻' },
      { value: 'parallel_urban', name: '平行都市' },
      { value: 'parallel_historical', name: '平行历史' },
      { value: 'parallel_universe', name: '平行宇宙' },
      { value: 'system', name: '系统流' },
      { value: 'game_system', name: '游戏系统' },
      { value: 'cultivation_system', name: '修炼系统' },
      { value: 'technology_system', name: '科技系统' },
      { value: 'reborn', name: '重生' },
      { value: 'historical_reborn', name: '历史重生' },
      { value: 'fantasy_reborn', name: '玄幻重生' },
      { value: 'mythology', name: '神话传说' },
      { value: 'detective', name: '侦探' },
      { value: 'western', name: '西部' },
      { value: 'comedy', name: '喜剧' },
      { value: 'tragedy', name: '悲剧' },
      { value: 'thriller', name: '惊悚' },
      { value: 'action', name: '动作冒险' },
      { value: 'spy', name: '间谍' },
      { value: 'legal', name: '法律' },
      { value: 'medical', name: '医疗' },
      { value: 'engineering', name: '工程技术' },
      { value: 'political', name: '政治' },
      { value: 'economics', name: '经济' },
      { value: 'educational', name: '教育' },
      { value: 'environmental', name: '环境' },
      { value: 'animal', name: '动物' },
      { value: 'film', name: '电影' },
      { value: 'television', name: '电视' },
      { value: 'internet', name: '互联网' },
      { value: 'space', name: '太空' },
      { value: 'alien', name: '外星人' },
      { value: 'robot', name: '机器人' },
      { value: 'virtual_reality', name: '虚拟现实' },
      { value: 'artificial_intelligence', name: '人工智能' },
      { value: 'cyberpunk', name: '赛博朋克' },
      { value: 'post_apocalyptic', name: '后启示录' },
      { value: 'steampunk', name: '蒸汽朋克' },
      { value: 'slice_of_life', name: '日常' },
      { value: 'coming_of_age', name: '成长' },
      { value: 'road_trip', name: '公路旅行' },
      { value: 'isekai', name: '异世界' },
      { value: 'ancient', name: '古代背景' },
      { value: 'modern', name: '现代背景' },
      { value: 'future', name: '未来背景' },
      { value: 'domestic', name: '国内小说' },
      { value: 'foreign', name: '国外小说' },
    ],
  },
  {
    key: 'status',
    name: '状态',
    children: [
      { value: 'serialize', name: '连载中' },
      { value: 'complete', name: '已完结' },
      { value: 'vip_only', name: 'VIP专属' },
      { value: 'finished', name: '已完结' },
      { value: 'unfinished', name: '未完结' },
      { value: 'hot', name: '热门' },
      { value: 'new', name: '新书' },
      { value: 'classic', name: '经典' },
      { value: 'male_author', name: '男作者' },
      { value: 'female_author', name: '女作者' },
      { value: 'known_author', name: '知名作者' },
      { value: 'unknown_author', name: '不知名作者' },
      { value: 'ancient', name: '古代背景' },
      { value: 'modern', name: '现代背景' },
      { value: 'future', name: '未来背景' },
      { value: 'domestic', name: '国内小说' },
      { value: 'foreign', name: '国外小说' },
      { value: 'male_frequency', name: '男频' },
      { value: 'female_frequency', name: '女频' },
      { value: 'subscribed', name: '订阅向' },
      { value: 'copyright', name: '版权向' },
      { value: 'original', name: '原创' },
      { value: 'fanfiction', name: '同人' },
    ],
  },
  {
    key: 'length',
    name: '字数',
    children: [
      { value: 'epic', name: '200万字以上' },
      { value: 'long', name: '长篇（100万字以上）' },
      { value: 'medium', name: '中篇（10万-100万字）' },
      { value: 'short', name: '短篇（10万字以下）' },
      { value: 'high_score', name: '高分（8分及以上）' },
      { value: 'medium_score', name: '中分（6-7.9分）' },
      { value: 'low_score', name: '低分（6分以下）' },
    ],
  },
  {
    key: 'payment',
    name: '付费类型',
    children: [
      { value: 'free', name: '免费' },
      { value: 'paid', name: '付费' },
      { value: 'vip', name: '会员' },
      { value: 'vip_free', name: '会员免费' },
      { value: 'limited_free', name: '限免中' },
    ],
  },
  {
    key: 'comprehensive_sorting',
    name: '综合排序',
    children: [
      { value: 'highest_heat', name: '热度最高' },
      { value: 'latest_release', name: '最新上线' },
      { value: 'most_reviews_positive', name: '最多好评' },
      { value: 'most_reviews_negative', name: '最多差评' },
      { value: 'most_comments', name: '最多评论' },
      { value: 'most_follows', name: '最多关注' },
      { value: 'most_collections', name: '最多收藏' },
      { value: 'most_likes', name: '最多点赞' },
      { value: 'most_watches', name: '最多观看' },
      { value: 'latest_update', name: '最新更新' },
      { value: 'most_downloads', name: '最多下载' },
      { value: 'recent_updates', name: '最近更新' },
      { value: 'most_awards', name: '最多获奖' },
    ],
  },
  {
    key: 'tag',
    name: '标签',
    children: [
      { value: 'children', name: '儿童' },
      { value: 'teen', name: '青少年' },
      { value: 'adult', name: '成人' },
      { value: 'training', name: '调教' },
      { value: 'married_woman', name: '人妻' },
      { value: 'mature', name: '熟女' },
      { value: 'harem', name: '后宫' },
      { value: 'power_fantasy', name: '爽文' },
      { value: 'NTR', name: 'NTR' },
      { value: 'seduction', name: '猎艳' },
      { value: 'plot', name: '剧情' },
      { value: 'corruption', name: '淫堕' },
      { value: 'mother_son', name: '母子' },
      { value: 'sex_slave', name: '性奴' },
      { value: 'abuse', name: '凌辱' },
      { value: 'isekai', name: '异世界' },
      { value: 'pure_love', name: '纯爱' },
      { value: 'uniform', name: '制服' },
      { value: 'contrast', name: '反差' },
      { value: 'stockings', name: '丝袜' },
      { value: 'group_sex', name: '群交' },
      { value: 'female_pov', name: '女性视角' },
      { value: 'rape', name: '强奸' },
      { value: 'netorare_mother', name: '绿母' },
      { value: 'SM', name: 'SM' },
      { value: 'campus_beauty', name: '校花' },
      { value: 'human_toilet', name: '肉便器' },
      { value: 'classic', name: '经典' },
      { value: 'quick_read', name: '手枪文' },
      { value: '1v1', name: '1v1' },
      { value: 'slutty', name: '痴女' },
      { value: 'toys', name: '道具' },
      { value: 'exhibitionism', name: '露出' },
      { value: 'cheating', name: '出轨' },
      { value: 'female_friendly', name: '适合女生' },
      { value: 'mother_daughter', name: '母女花' },
      { value: 'NTL', name: 'NTL' },
      { value: 'incest', name: '骨科' },
      { value: 'foreign', name: '异国' },
      { value: 'well_written', name: '好文笔' },
      { value: 'hypnosis', name: '催眠' },
      { value: 'protagonist_abuse', name: '虐主' },
      { value: 'NP', name: 'NP' },
      { value: 'mild_hardcore', name: '微重口' },
      { value: 'interspecies', name: '异种族' },
      { value: 'father_daughter', name: '父女' },
      { value: 'hardcore', name: '重口' },
      { value: 'wife_sharing', name: '淫妻' },
      { value: 'sweet', name: '甜文' },
      { value: 'officialdom', name: '官场' },
      { value: 'supernatural', name: '灵异' },
      { value: 'romantic', name: '浪漫' },
      { value: 'age_gap', name: '小马拉大车' },
      { value: 'sister_duo', name: '姐妹花' },
      { value: 'loli', name: '萝莉' },
      { value: 'yuri', name: '百合' },
      { value: 'milking', name: '榨精' },
      { value: 'no_netorare', name: '无绿' },
      { value: 'foot_fetish', name: '恋足' },
      { value: 'gender_bender', name: '性转' },
      { value: 'caught_in_act', name: '目前犯' },
      { value: 'partner_swap', name: '交换伴侣' },
      { value: 'impregnation', name: '受孕' },
      { value: 'dark', name: '暗黑' },
      { value: 'black_worship', name: '媚黑' },
      { value: 'foot_job', name: '足交' },
      { value: 'whole_family', name: '全家桶' },
      { value: 'mother_in_law', name: '公媳' },
      { value: 'harem', name: '种马' },
      { value: 'quick_transmigration', name: '快穿' },
      { value: 'revenge', name: '复仇' },
      { value: 'sadistic', name: '虐心' },
      { value: 'Futa', name: '扶她' },
      { value: 'last_phase', name: '末世' },
      { value: 'man_beast', name: '人兽' },
      { value: 'tyrannical', name: '暴虐' },
      { value: 'Lose_virginity', name: '破处' },
      { value: 'drug', name: '药物' },
      { value: 'HE', name: 'HE' },
      { value: 'milk', name: '产奶' },
      { value: 'Backwards', name: '逆推' },
      { value: 'gaol', name: '监禁' },
      { value: 'bundle', name: '捆绑' },
      { value: 'femboy', name: '伪娘' },
      { value: 'reform', name: '改造' },
      { value: 'Micro_meat', name: '微肉' },
      { value: 'Dog_blood', name: '狗血' },
      { value: 'Danmei', name: '耽美' },
      { value: 'tentacle', name: '触手' },
      { value: 'Hidden_adultery', name: '隐奸' },
      { value: 'SC', name: 'SC' },
      { value: 'Foul_language', name: '粗口' },
      { value: 'shemale', name: '人妖' },
      { value: 'green_slave', name: '绿奴' },
      { value: 'expansion', name: '扩张' },
      { value: 'Shenhao', name: '神豪' },
      { value: 'yandere', name: '病娇' },
      { value: 'farming', name: '种田' },
      { value: 'Cross_dressing', name: '变装' },
      { value: 'funny', name: '搞笑' },
      { value: 'BE', name: 'BE' },
      { value: 'Lower_overcomes_upper', name: '下克上' },
      { value: 'Exposed', name: '暴露' },
      { value: 'Group_P', name: '群P' },
      { value: 'Inverse_NTR', name: '逆NTR' },
      { value: 'teacher', name: '老师' },
      { value: 'Doujin', name: '同人' },
      { value: 'No_pubic_hair', name: '白虎' },
    ],
  },
]

// 图片相关分类
const pictureCategories = [
  {
    key: 'type',
    name: '类型',
    children: [
      { value: 'anime', name: '动漫' },
      { value: 'manga', name: '漫画' },
      { value: 'art', name: '艺术' },
      { value: 'design', name: '设计' },
      { value: 'life', name: '生活' },
      { value: 'entertainment', name: '娱乐' },
      { value: 'illustration', name: '插画' },
      { value: 'photo', name: '摄影' },
      { value: 'painting', name: '画作' },
      { value: 'photo_art', name: '知识' },
      { value: 'location', name: '地址' },
      { value: 'nature', name: '自然' },
      { value: 'people', name: '人物' },
      { value: 'vehicles', name: '车辆' },
      { value: 'ai_painting', name: 'AI绘画' },
      { value: 'game', name: '游戏' },
      { value: 'space', name: '太空' },
      { value: 'animal', name: '动物' },
      { value: 'food', name: '美食' },
      { value: 'travel', name: '旅游' },
      { value: 'street', name: '街拍' },
      { value: 'models', name: '模型' },
      { value: 'clothing', name: '服装' },
    ],
  },
  {
    key: 'format',
    name: '格式',
    children: [
      { value: 'gif', name: '动图' },
      { value: 'webp', name: 'webp' },
      { value: 'base64', name: 'base64' },
      { value: 'jpeg', name: 'jpeg' },
      { value: 'jpg', name: 'jpg' },
      { value: 'png', name: 'png' },
      { value: 'svg', name: 'svg' },
      { value: 'ico', name: 'ico' },
      { value: 'jpeg2000', name: 'jpeg2000' },
      { value: 'apng', name: 'apng' },
      { value: 'avif', name: 'avif' },
      { value: 'tiff', name: 'tiff' },
      { value: 'psd', name: 'psd' },
      { value: 'blender', name: 'blender' },
    ],
  },
  {
    key: 'proportion',
    name: '比例',
    children: [
      { value: '4K', name: '3840_2160' },
      { value: '2K', name: '2560_1440' },
      { value: '1080P', name: '1920_1080' },
      { value: '169S', name: '1280_720' },
      { value: '169M', name: '1600_900' },
      { value: '169L', name: '5160_3840' },
      { value: '1610P', name: '1280_800' },
      { value: '1610S', name: '1600_1000' },
      { value: '1610M', name: '1920_1200' },
      { value: '1610L', name: '2560_1600' },
      { value: '1610B', name: '3840_2400' },
      { value: '43P', name: '1280_960' },
      { value: '43S', name: '1600_1200' },
      { value: '43M', name: '1920_1440' },
      { value: '43L', name: '2560_1920' },
      { value: '43B', name: '3840_2880' },
      { value: '54P', name: '1280_1024' },
      { value: '54S', name: '1600_1280' },
      { value: '54M', name: '1920_1536' },
      { value: '54L', name: '2560_2048' },
      { value: '54B', name: '3840_3072' },
    ],
  },
  {
    key: 'color',
    name: '颜色',
    children: [
      { value: 'red', name: '红色' },
      { value: 'yellow', name: '黄色' },
      { value: 'blue', name: '蓝色' },
      { value: 'green', name: '绿色' },
      { value: 'purple', name: '紫色' },
      { value: 'orange', name: '橙色' },
      { value: 'pink', name: '粉色' },
      { value: 'brown', name: '棕色' },
      { value: 'gray', name: '灰色' },
      { value: 'black', name: '黑色' },
      { value: 'white', name: '白色' },
      { value: 'gold', name: '金色' },
      { value: 'silver', name: '银色' },
      { value: 'beige', name: '米色' },
      { value: 'navy', name: '深蓝色' },
      { value: 'cyan', name: '青色' },
      { value: 'magenta', name: '品红' },
      { value: 'maroon', name: '栗色' },
      { value: 'olive', name: '橄榄绿' },
      { value: 'teal', name: '青绿色' },
    ],
  },
  {
    key: 'tag',
    name: '标签',
    children: [
      { value: 'looking_at_viewer', name: '注视观众' },
      { value: 'huge_breasts', name: '巨乳' },
      { value: 'blushing', name: '脸红' },
      { value: 'bent_over', name: '弯腰' },
      { value: 'women_outdoors', name: '户外女性' },
      { value: 'water', name: '水' },
      { value: 'tongue_out', name: '吐舌' },
      { value: 'flower_in_hair', name: '头发上的花' },
      { value: 'saliva_trail', name: '唾液痕迹' },
      { value: 'holding_boobs', name: '抱住胸部' },
      { value: 'hard_nipples', name: '坚挺乳头' },
      { value: 'wet_body', name: '湿身' },
      { value: 'wet_clothing', name: '湿衣服' },
      { value: 'white_towel', name: '白毛巾' },
      { value: 'cleavage', name: '胸沟' },
      { value: 'hair_ornament', name: '发饰' },
      { value: 'depth_of_field', name: '景深' },
      { value: 'saliva', name: '唾液' },
      { value: 'pink_hair', name: '粉色头发' },
      { value: 'long_hair', name: '长发' },
      { value: 'nipples_through_clothing', name: '透衣乳头' },
      { value: 'arched_back', name: '拱背' },
      { value: 'sky', name: '天空' },
      { value: 'steam', name: '蒸汽' },
      { value: 'blue_eyes', name: '蓝眼睛' },
      { value: 'onsen', name: '温泉' },
      { value: 'nude', name: '裸体' },
      { value: 'boobs', name: '胸部' },
      { value: 'vulva', name: '阴部' },
      { value: 'tattoo', name: '纹身' },
      { value: 'black_stockings', name: '黑色长袜' },
      { value: 'blonde', name: '金发' },
      { value: 'legs', name: '腿' },
      { value: 'tiptoe', name: '踮脚' },
      { value: 'doorways', name: '门口' },
      { value: 'armpits', name: '腋下' },
      { value: 'hips', name: '臀部' },
      { value: 'tan_lines', name: '晒痕' },
      { value: 'belly_button', name: '肚脐' },
      { value: 'ribs', name: '肋骨' },
      { value: 'wooden_floor', name: '木地板' },
      { value: 'white_couch', name: '白色沙发' },
      { value: 'Russian', name: '俄罗斯' },
      { value: 'portrait_display', name: '肖像展示' },
      { value: 'wet_hair', name: '湿发' },
      { value: 'hand(s)_on_chest', name: '手放在胸部' },
      { value: 'leaves', name: '叶子' },
      { value: 'watermarked', name: '水印' },
      { value: 'collarbone', name: '锁骨' },
      { value: 'video_games', name: '视频游戏' },
      { value: 'video_game_girls', name: '视频游戏女孩' },
      { value: 'CGI', name: '计算机生成图像' },
      { value: 'digital_art', name: '数字艺术' },
      { value: 'fan_art', name: '同人艺术' },
      { value: 'Final_Fantasy_VII', name: '最终幻想VII' },
      { value: 'Final_Fantasy_VII:_Remake', name: '最终幻想VII：重制版' },
      { value: 'Final_Fantasy_VII:_Rebirth', name: '最终幻想VII：重生' },
      { value: 'Square_Enix', name: '史克威尔艾尼克斯' },
      { value: 'mrvargas', name: 'mrvargas' },
      { value: 'Seltin_Sweet', name: 'Seltin Sweet' },
      { value: 'Joakim_Karlsson', name: 'Joakim Karlsson' },
      { value: 'Sonya_Blaze', name: 'Sonya Blaze' },
      { value: 'brunette', name: '棕色头发' },
      { value: 'model', name: '模特' },
      { value: 'shaved pubic hair', name: '剃光的阴毛' },
      { value: 'plants', name: '植物' },
      { value: 'standing', name: '站立' },
      { value: 'hips', name: '臀部' },
      { value: 'legs', name: '腿' },
      { value: 'tiptoe', name: '踮脚' },
      { value: 'belly_button', name: '肚脐' },
      { value: 'ribs', name: '肋骨' },
      { value: 'wooden_floor', name: '木地板' },
      { value: 'white_couch', name: '白色沙发' },
      { value: 'Russian_women', name: '俄罗斯女性' },
      { value: 'Russian', name: '俄罗斯' },
    ],
  },
]

// 漫画相关分类
const comicCategories = [
  {
    key: 'type',
    name: '类型',
    children: [
      { value: 'life', name: '生活' },
      { value: 'fantasy', name: '奇幻' },
      { value: 'horror', name: '恐怖' },
      { value: 'romance', name: '浪漫' },
      { value: 'action', name: '动作' },
      { value: 'adventure', name: '冒险' },
      { value: 'mystery', name: '悬疑' },
      { value: 'slice_of_life', name: '生活片段' },
      { value: 'historical', name: '历史' },
      { value: 'superhero', name: '超级英雄' },
      { value: 'sports', name: '运动' },
      { value: 'supernatural', name: '超自然' },
    ],
  },
  {
    key: 'genre',
    name: '题材',
    children: [
      { value: 'shounen', name: '少年' },
      { value: 'shoujo', name: '少女' },
      { value: 'seinen', name: '青年' },
      { value: 'josei', name: '女性' },
      { value: 'manhua', name: '漫画' },
      { value: 'manhwa', name: '韩漫' },
      { value: 'yaoi', name: '耽美' },
      { value: 'yuri', name: '百合' },
    ],
  },
  {
    key: 'tags',
    name: '标签',
    children: [
      { value: 'action', name: '动作' },
      { value: 'romance', name: '浪漫' },
      { value: 'comedy', name: '喜剧' },
      { value: 'drama', name: '剧情' },
      { value: 'fantasy', name: '奇幻' },
      { value: 'sci-fi', name: '科幻' },
      { value: 'mature', name: '成人' },
      { value: 'mystery', name: '悬疑' },
    ],
  },
  {
    key: 'rating',
    name: '分级',
    children: [
      { value: 'G', name: '适合所有人' },
      { value: 'PG', name: '家长指导' },
      { value: 'PG-13', name: '13岁以上' },
      { value: 'R', name: '限制级' },
      { value: 'NC-17', name: '17岁以上' },
    ],
  },
]

// 游戏相关分类
const gameCategories = [
  {
    key: 'type',
    name: '类型',
    children: [
      { value: 'action', name: '动作' },
      { value: 'adventure', name: '冒险' },
      { value: 'rpg', name: '角色扮演' },
      { value: 'shooter', name: '射击' },
      { value: 'strategy', name: '策略' },
      { value: 'simulation', name: '模拟' },
      { value: 'puzzle', name: '益智' },
      { value: 'sports', name: '体育' },
      { value: 'fighting', name: '格斗' },
      { value: 'platformer', name: '平台' },
      { value: 'horror', name: '恐怖' },
      { value: 'sandbox', name: '沙盒' },
      { value: 'battle_royale', name: '大逃杀' },
      { value: 'card', name: '卡牌' },
      { value: 'idle', name: '放置' },
      { value: 'MMORPG', name: '大型多人在线角色扮演' },
      { value: 'roguelike', name: '类银河战士' },
    ],
  },
  {
    key: 'genre',
    name: '题材',
    children: [
      { value: 'fantasy', name: '奇幻' },
      { value: 'sci-fi', name: '科幻' },
      { value: 'historical', name: '历史' },
      { value: 'horror', name: '恐怖' },
      { value: 'mystery', name: '悬疑' },
      { value: 'romance', name: '浪漫' },
      { value: 'wasteland', name: '废土' },
    ],
  },
  {
    key: 'tags',
    name: '标签',
    children: [
      { value: 'multiplayer', name: '多人' },
      { value: 'singleplayer', name: '单人' },
      { value: 'co-op', name: '合作' },
      { value: 'open_world', name: '开放世界' },
      { value: 'story_driven', name: '剧情驱动' },
      { value: 'competitive', name: '竞技' },
      { value: 'casual', name: '休闲' },
      { value: 'mature', name: '成人' },
    ],
  },
  {
    key: 'rating',
    name: '分级',
    children: [
      { value: 'E', name: '适合所有人' },
      { value: 'E10+', name: '适合10岁以上' },
      { value: 'T', name: '适合13岁以上' },
      { value: 'M', name: '适合17岁以上' },
      { value: 'AO', name: '成人仅限' },
    ],
  },
]

// 音频相关分类
const audioCategories = [
  {
    key: 'category',
    name: '分类',
    children: [
      { value: 'original_music', name: 'Original Music' }, // 原创音乐
      { value: 'live_performance', name: 'Live Performance' }, // 音乐现场
      { value: 'cover', name: 'Cover' }, // 翻唱
      { value: 'instrumental', name: 'Instrumental' }, // 演奏
      { value: 'music_scene', name: 'Music Scene' }, // 乐坛
      { value: 'synthesizer_music', name: 'Synthesizer Music' }, // 合成音乐
      { value: 'mv', name: 'Music Video' }, // MV
      { value: 'virtual_singer', name: 'Virtual Singer' }, // 虚拟歌手
      { value: 'ai_music', name: 'AI Music' }, // AI音乐
      { value: 'radio', name: 'Radio' }, // 电台
      { value: 'music_education', name: 'Music Education' }, // 音乐教学
    ],
  },
  {
    key: 'genre',
    name: '流派',
    children: [
      { value: 'rap', name: 'Rap' }, // 说唱
      { value: 'hip_hop', name: 'HIPHOP' }, // 街舞表演
      { value: 'chinese_style', name: 'Chinese Style' }, // 中国风
      { value: 'ancient_style', name: 'Ancient Style' }, // 古风
      { value: 'electronic', name: 'Electronic' }, // 电音
      { value: 'rock', name: 'Rock' }, // 摇滚
      { value: 'folk', name: 'Folk' }, // 民谣
      { value: 'classic', name: '古典' }, // 古典
      { value: 'jazz', name: 'Jazz' }, // 爵士
      { value: 'instrumental', name: 'Instrumental' }, // 纯音乐
      { value: 'bgm', name: 'Background Music' }, // BGM
      { value: 'beat', name: 'Beat' }, // BEAT
      { value: 'remix', name: 'Remix' }, // REMIX
      { value: 'vocal_original', name: 'Vocal Original' }, // 人声本家
      { value: 'chinese_original', name: 'Chinese Original' }, // 国人原创
      { value: 'original_song', name: 'Original Song' }, // 原创歌曲
      { value: 'arrangement', name: 'Arrangement' }, // 编曲
      { value: 'adaptation', name: 'Adaptation' }, // 改编
      { value: 'guitar', name: 'Guitar' }, // 吉他
      { value: 'electronic_music', name: 'Electronic Music' }, // 电子音乐
      { value: 'piano', name: 'Piano' }, // 钢琴
    ],
  },
  {
    key: 'scene',
    name: '乐坛',
    children: [
      { value: 'chinese_live', name: 'Chinese Live' }, // 华语现场
      { value: 'english_live', name: 'English Live' }, // 欧美现场
      { value: 'japanese_live', name: 'Japanese Live' }, // 日语现场
      { value: 'korean_live', name: 'Korean Live' }, // 韩语现场
      { value: 'mandarin_live', name: 'Mandarin Live' }, // 国语现场
      { value: 'cantonese_live', name: 'Cantonese Live' }, // 粤语现场
      { value: 'live_performance', name: 'Live Performance' }, // live现场
      { value: 'musical', name: 'Musical' }, // 音乐剧
      { value: 'concert', name: 'Concert' }, // 演唱会
      { value: 'music_festival', name: 'Music Festival' }, // 音乐节
    ],
  },
  {
    key: 'cover',
    name: '翻唱',
    children: [
      { value: 'male_vocal', name: 'Male Vocal' }, // 男声
      { value: 'female_vocal', name: 'Female Vocal' }, // 女声
      { value: 'chinese_cover', name: 'Chinese Cover' }, // 中文翻唱
      { value: 'english_cover', name: 'English Cover' }, // 英文翻唱
      { value: 'japanese_cover', name: 'Japanese Cover' }, // 日文翻唱
      { value: 'korean_cover', name: 'Korean Cover' }, // 韩语翻唱
      { value: 'ancient_style', name: 'Ancient Style' }, // 古风
      { value: 'burning_genre', name: 'Burning Genre' }, // 燃向
      { value: 'chinese_lyric', name: 'Chinese Lyric' }, // 中文填词
      { value: 'chinese_cover_artist', name: 'Chinese Cover Artist' }, // 国人翻唱
      { value: 'soul_singer', name: 'Soul Singer' }, // 灵魂歌手
      { value: 'healing', name: 'Healing' }, // 治愈系
      { value: 'cover', name: 'Cover' }, // 翻唱
      { value: 'guitar_cover', name: 'Guitar Cover' }, // 吉他翻唱
      { value: 'vocaloid', name: 'Vocaloid' }, // 发声体
      { value: 'original_pv', name: 'Original PV' }, // 原创PV
      { value: 'english', name: 'English' }, // 欧美
      { value: 'new_artist', name: 'New Artist' }, // 新人
    ],
  },
  {
    key: 'instrument',
    name: '乐器演奏',
    children: [
      { value: 'guitar', name: '吉他' },
      { value: 'bass', name: '贝斯' },
      { value: 'drums', name: '鼓' },
      { value: 'performance', name: '演奏' },
      { value: 'piano', name: '钢琴' },
      { value: 'street_performance', name: '街头表演' },
      { value: 'finger_picking', name: '翻弹' },
      { value: 'band', name: '乐队' },
      { value: 'traditional_music', name: '民乐' },
      { value: 'ensemble', name: '合奏' },
      { value: 'fingerstyle', name: '指弹' },
      { value: 'violin', name: '小提琴' },
      { value: 'snare_drums', name: '架子鼓' },
      { value: 'acoustic_guitar', name: '木吉他' },
      { value: 'bgm', name: '背景音乐' },
      { value: 'flute', name: '卡祖笛' },
      { value: 'electric_guitar', name: '电吉他' },
      { value: 'harmonica', name: '口琴' },
      { value: 'fingerstyle_guitar', name: '指弹吉他' },
      { value: 'yangqin', name: '扬琴' },
      { value: 'gu Zheng', name: '古筝' },
      { value: 'erhu', name: '二胡' },
      { value: 'beatbox', name: 'Beatbox' },
      { value: 'launchpad', name: 'Launchpad' },
      { value: 'xun', name: '埙' },
      { value: 'dizi', name: '箫' },
      { value: 'flute_chinese', name: '笛子' },
      { value: 'guqin', name: '古琴' },
    ],
  },
  {
    key: 'singer',
    name: '歌手',
    children: [
      { value: '洛天依', name: 'Luo Tianyi' },
      { value: '乐正绫', name: 'Yue Zheng Ling' },
      { value: '言和', name: 'Yan He' },
      { value: '乐正龙牙', name: 'Yue Zheng Longya' },
      { value: '墨清弦', name: 'Mo Qingxian' },
      { value: '徵羽摩柯', name: 'Zheng Yu Mo Ke' },
      { value: '虚拟歌手', name: 'Vsinger' },
      { value: '心华', name: 'Xin Hua' },
      { value: '星尘', name: 'Xing Chen' },
      { value: '赤羽', name: 'chi yu' },
      { value: '嫣汐', name: 'yan xi' },
      { value: '初音未来', name: 'chu yin wei lai' },
      { value: '镜音铃', name: 'jing yin ling' },
      { value: '镜音连', name: 'jing yin lian' },
      { value: '巡音流歌', name: 'xun yin liu ge' },
      { value: 'KAITO', name: 'kaito' },
      { value: '元筱', name: 'yuan xiao' },
      { value: 'flower', name: 'hua er' },
      { value: '莲华', name: 'lian hua' },
      { value: '南北组', name: 'bei nan zu' },
      { value: '镜音双子', name: 'jing yin' },
      { value: 'MUTA中文曲', name: 'muta' },
      { value: 'UTAU中华组', name: 'utau' },
      { value: 'XStudio', name: 'x studio' },
      { value: 'IA', name: 'ia' },
      { value: 'GUMI', name: 'gumi' },
      { value: 'SynthV', name: 'synthv' },
      { value: 'UTAU', name: 'utau' },
      { value: '幻晓伊', name: 'huan xiao yi' },
      { value: '五维介质', name: 'wu wei ji zhi' },
      { value: '可不', name: 'ke bu' },
      { value: 'ACE虚拟歌姬', name: 'ace' },
      { value: 'deepvocal', name: 'deepvocal' },
      { value: 'SYNTHV', name: 'synthv' },
    ],
  },
  {
    key: 'music_video',
    name: '音乐MV',
    children: [
      { value: 'Chinese_MV', name: '华语MV' },
      { value: 'English_MV', name: '欧美MV' },
      { value: 'Japanese_MV', name: '日语MV' },
      { value: 'Korean_MV', name: '韩语MV' },
      { value: 'Mandarin_MV', name: '国语MV' },
      { value: 'Cantonese_MV', name: '粤语MV' },
      { value: 'Southeast_Asian_MV', name: '东南亚MV' },
      { value: 'Russian_MV', name: '俄语MV' },
      { value: 'User_made_MV', name: '自制MV' },
      { value: 'Remake', name: '翻拍' },
      { value: 'Mixed_MV', name: '混剪MV' },
      { value: '4K', name: '4K' },
      { value: '2K', name: '2K' },
      { value: '1080P', name: '1080P' },
    ],
  },
  {
    key: 'AI_music',
    name: 'AI音乐',
    children: [
      { value: 'AI_Song', name: 'AI歌曲' },
      { value: 'Suno', name: 'Suno' },
      { value: 'AI_Cover', name: 'AI翻唱' },
      { value: 'Sovits', name: 'Sovits' },
      { value: 'RVC', name: 'RVC' },
      { value: 'AI_Dubbing', name: 'AI配音' },
      { value: 'AI_Arrangement', name: 'AI编曲' },
      { value: 'AI_Composition', name: 'AI作曲' },
      { value: 'AI_Lyrics', name: 'AI作词' },
      { value: 'AI_Voice Change', name: 'AI变声' },
      { value: 'Diff_svc', name: 'Diff-svc' },
    ],
  },
  {
    key: 'radio',
    name: '电台',
    children: [
      { value: 'music_share', name: '音乐分享' },
      { value: 'Playlist', name: 'Playlist' },
      { value: 'White_Noise', name: '白噪音' },
      { value: 'Instrumental_Music', name: '纯音乐' },
      { value: 'Audio_books', name: '有声读物' },
      { value: 'Podcast', name: '播客' },
      { value: 'Sleep_Aid', name: '助眠' },
      { value: 'Radio', name: '电台' },
      { value: 'Dubbing', name: '配音' },
      { value: 'Audiobook', name: '听书' },
      { value: 'Audio_Drama', name: '广播剧' },
    ],
  },
  {
    key: 'music_teach',
    name: '音乐教学',
    children: [
      { value: 'singing_teaching', name: '唱歌教学' },
      { value: 'guitar_teaching', name: '吉他教学' },
      { value: 'piano_teaching', name: '钢琴教学' },
      { value: 'electronic_music_tutorial', name: '电音教程' },
      { value: 'music_arrangement', name: '编曲' },
      { value: 'audio_mixing', name: '混音' },
      { value: 'music_theory', name: '乐理' },
      { value: 'music_production', name: '音乐制作' },
      { value: 'music_composition', name: '作曲' },
      { value: 'bel_canto', name: '美声' },
      { value: 'singing_skills', name: '唱歌技巧' },
      { value: 'BBOX', name: 'BBOX' },
      { value: 'accompaniment', name: '伴奏' },
      { value: 'classical_music', name: '古典音乐' },
      { value: 'REMIX', name: 'REMIX' },
      { value: 'chord', name: '和弦' },
      { value: 'transcribing_music', name: '扒谱' },
    ],
  },
]

// 商品相关分类
const shopCategories = [
  {
    key: 'electronics',
    name: '电子产品',
    children: [
      { value: 'mobile', name: '手机' },
      { value: 'laptop', name: '笔记本电脑' },
      { value: 'tablet', name: '平板电脑' },
      { value: 'camera', name: '相机' },
      { value: 'headphones', name: '耳机' },
      { value: 'smartwatch', name: '智能手表' },
    ],
  },
  {
    key: 'home_appliances',
    name: '家用电器',
    children: [
      { value: 'refrigerator', name: '冰箱' },
      { value: 'washing_machine', name: '洗衣机' },
      { value: 'microwave', name: '微波炉' },
      { value: 'air_conditioner', name: '空调' },
      { value: 'vacuum_cleaner', name: '吸尘器' },
    ],
  },
  {
    key: 'clothing',
    name: '服装',
    children: [
      { value: 'men_clothing', name: '男装' },
      { value: 'women_clothing', name: '女装' },
      { value: 'children_clothing', name: '童装' },
      { value: 'shoes', name: '鞋子' },
      { value: 'accessories', name: '配饰' },
    ],
  },
  {
    key: 'beauty',
    name: '美容护肤',
    children: [
      { value: 'skincare', name: '护肤品' },
      { value: 'makeup', name: '化妆品' },
      { value: 'fragrance', name: '香水' },
      { value: 'hair_care', name: '护发产品' },
    ],
  },
  {
    key: 'grocery',
    name: '食品',
    children: [
      { value: 'snacks', name: '零食' },
      { value: 'beverages', name: '饮料' },
      { value: 'fresh_food', name: '生鲜食品' },
      { value: 'canned_food', name: '罐头食品' },
    ],
  },
  {
    key: 'furniture',
    name: '家具',
    children: [
      { value: 'living_room', name: '客厅家具' },
      { value: 'bedroom', name: '卧室家具' },
      { value: 'office', name: '办公家具' },
      { value: 'kitchen', name: '厨房家具' },
    ],
  },
]

// 导出所有分类
const FilterTypeData = {
  video: videoCategories,
  book: bookCategories,
  picture: pictureCategories,
  comic: comicCategories,
  game: gameCategories,
  audio: audioCategories,
  shop: shopCategories,
}

// 为了兼容全局变量方式
window.DC = window.DC || {}
window.DC.FilterTypeData = FilterTypeData

// export default FilterTypeData;
